 version: "3.9"
 services:
   backend:
     build: .
     ports:
       - "8000:8000"
     volumes:
       - .:/app
     depends_on:
       - postgres
   postgres:
     container_name: atiweb-pg
     image: postgres
     environment:
       POSTGRES_USER: atiuser
       POSTGRES_PASSWORD: atipassword
       POSTGRES_DB: atiweb
       PGDATA: /data/postgres
     volumes:
       - ./postgres:/data/postgres
     ports:
       - "5432:5432"
     restart: unless-stopped












#  version: "3.9"
#  services:
#    backend:
#      build: .
#      ports:
#        - "3000:3000"
#      volumes:
#        - .:/app

#      depends_on:
#        - db

#    db:
#     image: mysql:8.0.30
#     restart: always
#     environment:
#       MYSQL_DATABASE: ambassador
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - .dbdata:/var/lib/mysql
#     ports:
#         - 33066:3306

  
